spring:
  application:
    name: store-service
  datasource:
    url: jdbc:mysql://localhost:3306/store-db
    username: store_user
    password: store_user_pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8005
  servlet:
    context-path: /store-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/